# Generated by Django 6.0 on 2026-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electronics",
            name="sku",
        ),
        migrations.AlterField(
            model_name="electronics",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
