# Generated by Django 6.0 on 2026-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_electronics_sku_alter_electronics_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="electronics",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
