# Generated by Django 6.0 on 2026-04-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_electronics_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electronics",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="electronics",
            name="updated_at",
        ),
    ]
